### ISSUE TITLE
Fields Incorrect

### ISSUE THREAD

**Issue by JammyB** [Azure/azure-docs-powershell-samples#380]
The PBI Template is looking at an old column for estimates.

Compute monthly cost USD in PBI, is now Compute monthly cost estimate USD and the same for storage

**Comment by mikefrobbins** [comment]
@JammyB Thank you for reporting the issue. Please provide the name of the sample or a link to the sample that you're experiencing issues with. Also, if an error message is generated when attempting to use the referenced sample, please provide it.

**Comment by JammyB** [comment]
![image](https://user-images.githubusercontent.com/68296276/213996057-10999b27-479d-4701-b3fa-0f28bb18ec99.png)

![image](https://user-images.githubusercontent.com/68296276/213996232-4b70250f-52b2-4942-ad38-9919a11561ea.png)

**Comment by ekleidaras** [comment]
Hello both @mikefrobbins what @JammyB mentioned above is that the new labels that are produced by default at the exported assessment excel files have differences whit what PowerBI is configured for.

_Differences_  

Sample files vs Actual files downloaded currently from Azure

1. On your sample files on the worksheet "All_Assessed_Machines" the Column G label is "Compute monthly cost USD" on the new exported files the column label is "Compute monthly cost **_estimate_** USD".
2. On your sample files on the worksheet "All_Assessed_Machines" the Column H label is "Storagemonthly cost USD" on the new exported files the column label is "Storage monthly cost **_estimate_** USD".
3. On your sample files on the worksheet "Assessment_Summary" the cells A16 label is "Compute monthly cost USD" on the new exported files the column label is "Compute monthly cost **_estimate_** USD"
4. The same happens for the labels on the cells A17 to A20 on the same worksheet.

![Screenshot 2023-01-26 215231](https://user-images.githubusercontent.com/122875396/214936432-bfb496e0-8271-4c9a-a9f5-d26928b02424.png)

Also there is an issue when the assessment is made in other currency. Like Euro. 

What i did till now to manage run the PowerBI (cause I prepared only two assessments), was to go on my exported files and changed the label values to mach with the old values, and it works without the issues mentioned above.

It would be nice if you may apply the above changes. 

One last question, when you want to process an AS-IS report and a Performance based report Average CPU remains blank most probably because the AS-IS report does not have a value but text "Not Applicable"
![not applicable](https://user-images.githubusercontent.com/122875396/214940565-ce3ceb13-0d89-4209-bb4d-300719316107.png)
![Average CPU](https://user-images.githubusercontent.com/122875396/214940571-501f874f-7991-41cf-bf62-0ac9917087a3.png)


If the values changed to a number (I updated the non applicable to zero for both CPU and RAM) it works like a charm.

![Average CPU2](https://user-images.githubusercontent.com/122875396/214941108-5c7da188-67b3-4a21-b58e-5746fbcbf0bb.png)

**Comment by mikefrobbins** [comment]
@ekleidaras or @JammyB, Which file in this repo is causing the problem? Is there a link or sample script in documentation somewhere that guided you to this repo?

The files in this repo are sample scripts and artifacts for Azure PowerShell documentation. Once I know which file is causing the problem, I'll contact the appropriate service team to take a look at it.

**Comment by ekleidaras** [comment]
@mikefrobbins the file on this repo that is producing the issue is the "Azure Migrate Assessment Comparison PowerBI Template.pbit".

**Comment by mikefrobbins** [comment]
**Azure Migrate Export (AME)** replaced the **Azure Migrate Assessment Comparison PowerBI Template** found in this repo.

[AME Documentation](https://aka.ms/azuremigrateexportdocumentation)
[Download the required Utility Package]( https://aka.ms/azuremigrateexport)

Additional links:
[AME Sample Presentation](https://aka.ms/amepresentationAME)
[Sample Reports](https://aka.ms/amesamplereportsAME)
[Demo and Training Video](https://aka.ms/amedemovideo)

I'll update this repo to reflect this information and search our docs for any outdated links pointing to the Azure Migrate Assessment Comparison PowerBI Template in this repo.

**Comment by ekleidaras** [comment]
@mikefrobbins The additional links does not work  

Additional links:
[AME Sample Presentation](https://aka.ms/amepresentationAME) --> May be this link should be `https://aka.ms/amepresentation` and not `https://aka.ms/amepresentationAME`
[Sample Reports](https://aka.ms/amesamplereportsAME) --> May be this link should be `https://aka.ms/amesamplereports` and not `https://aka.ms/amesamplereportsAME`
[Demo and Training Video](https://aka.ms/amedemovideo) --> This is not accessible.

Event if i tried the above corrections on the links i got the same message for all of them

![external sharing](https://user-images.githubusercontent.com/122875396/215158650-6c871460-e212-4bf2-b8fc-dc70be16b8e2.png)

Could you please validate the url's again?

Thank you.

**Comment by mikefrobbins** [comment]
@ekleidaras Thanks for reporting the issues with the additional links. I've removed them for now and sent a message to the service team asking if they can make them available externally.

**Comment by ekleidaras** [comment]
@mikefrobbins Is there any update on this? Thank you!

**Comment by mikefrobbins** [comment]
@ekleidaras No updates, but I'd recommend logging an issue in the [azure-migrate-export repo](https://github.com/Azure/azure-migrate-export) since this is out of the scope of the samples located in this repo.
