### ISSUE TITLE
Username Password Authentication

### ISSUE THREAD

**Issue by robhiitsd** [Azure/azure-docs-powershell-samples#382]
With MFA enabled, this script does not work as it calls to enter username and password. 
Getting the following error: 
WARNING: Unable to acquire token for tenant 'organizations' with error 'UsernamePasswordCredential authentication
failed: Unsupported User Type 'Unknown'. Please see https://aka.ms/msal-net-up.
See the troubleshooting guide for more information.
https://aka.ms/azsdk/net/identity/usernamepasswordcredential/troubleshoot'
Is there a way to bypass asking for creds since the PS session is already authenticated and connected to the tenant?

**Comment by mikefrobbins** [comment]
@robhiitsd Please provide the URL or name of the script you're experiencing issues with.

**Comment by robhiitsd** [comment]
Register-SqlVMs.psm1
https://github.com/Azure/azure-docs-powershell-samples/blob/master/sql-virtual-machine/register-sql-vms/RegisterSqlVMs.psm1

**Comment by robhiitsd** [comment]
Will this run in older versions of Powershell even with MFA enabled for all accounts in our tenant? 
That option in the link unfortunately did not work for us and the support ticket I have with MS referenced me to attempt your solution, which doesn't work.

**Comment by ranishan** [comment]
You can try on Powershell 5.x. I am not aware of edge cases where it will not work on MFA enabled accounts.
Another option you can try would be to comment out the code that uses "Connect-AzAccount" and connect to your subscription using MFA in the same powershell session before running the script.

@robhiitsd  Do you know why the other solution I suggested doesn't work for you. Is it because you have limited access on the subscription?

**Comment by mikefrobbins** [comment]
Closing this issue based on @ranishan's response.
